
http {

    server {
        client_max_body_size 1000000;
        listen 127.0.0.1:8080;
        server_name webserver1.com example.com localhost;
        
        root /home/hrv/Documents/DEV/servweb/webserv/servers/server;
        index index.html index.php;
        
        error_page 404 /errors/404.html;
        error_page 500 /errors/500.html;

        location /bootstrap/ {
            root /home/hrv/Documents/DEV/servweb/webserv/servers;
            methods GET;
        }

        location /test {
            root /home/hrv/Documents/DEV/servweb/webserv/servers/server/;
            index index.html;
            methods POST GET DELETE;
            autoindex on;
        }

        location / {
            root /home/hrv/Documents/DEV/servweb/webserv/clients/www1;
            index index.html;
            methods GET POST DELETE;
            autoindex off;
        }

        location /cgi_bin {
            root /home/hrv/Documents/DEV/servweb/webserv/clients/www1/cgi_bin;
            cgi_extension .php;
            cgi_path /usr/bin/php-cgi;
        }

    }

    server {
        client_max_body_size 1000000;
        listen 127.0.0.1:8081;
        server_name webserver2.com;

        root /home/hrv/Documents/DEV/servweb/webserv/clients/www2;
        index index.html;

        error_page 404 /errors/404.html;
        error_page 500 /errors/500.html;

        location /bootstrap/ {
            root /home/hrv/Documents/DEV/servweb/webserv/servers;
            methods GET;
        }

        location / {
            root /home/hrv/Documents/DEV/servweb/webserv/clients/www2;
            index index.html;
            methods GET POST DELETE;
            autoindex off;
        }

        location /files {
            root /home/hrv/Documents/DEV/servweb/webserv/servers/server/;
            index index.html;
            methods POST GET DELETE;
            autoindex on;
        }

        location /cgi_bin {
            root /home/hrv/Documents/DEV/servweb/webserv/clients/www2/cgi_bin;
            cgi_extension .php;
            cgi_path /usr/bin/php-cgi;
        }
    }
}