
http {

    server {
        client_max_body_size 1000000;
        listen 127.0.0.1:8080;
        
        root /home/rhanitra/GITHUB/servweb/webserv/servers/server_1;
        index index.html index.php;
        
        error_page 404 /errors/404.html;
        error_page 500 /errors/500.html;

        location /bootstrap/ {
            root /home/rhanitra/GITHUB/servweb/webserv/servers;
            methods GET;
        }

        location /uploads {
            root /home/rhanitra/GITHUB/servweb/webserv/servers/server_1;
            methods POST GET;
        }

        location /test {
            root /home/rhanitra/GITHUB/servweb/webserv/servers/server_1/;
            methods POST GET DELETE;
        }

        location / {
            root /home/rhanitra/GITHUB/servweb/webserv/clients/www1;
            index index.html index.php;
            methods GET POST DELETE;
            autoindex off;
        }

        location /contact {
            root /home/rhanitra/GITHUB/servweb/webserv/clients/www1;
            index index.html;
            methods GET POST;
        }

        location /downloads {
            root /home/rhanitra/GITHUB/servweb/webserv/clients/www1;
            index index.html;
            methods GET POST;
        }

        location /cgi_test {
            root /home/rhanitra/GITHUB/servweb/webserv/clients/www1/cgi_test;
            cgi_extension .php;
            cgi_path /usr/bin/php-cgi;
        }

    }


}