http {

    server {
        client_max_body_size 1000000;
        listen 127.0.0.1:9998;
        server_name webserv_unique.com;
        
        root /home/rivoinfo/Documents/DEV/servwebs/webserv/clients/www1;
        index index.html;
        
        location / {
            root /home/rivoinfo/Documents/DEV/servwebs/webserv/clients/www1;
            index index.html;
            methods GET POST DELETE;
        }
    }

    server {
        client_max_body_size 1000000;
        listen 127.0.0.1:9999;
        server_name webserv_dup1.com;
        
        root /home/rivoinfo/Documents/DEV/servwebs/webserv/clients/www1;
        index index.html;
        
        location / {
            root /home/rivoinfo/Documents/DEV/servwebs/webserv/clients/www1;
            index index.html;
            methods GET POST DELETE;
        }
    }

    server {
        client_max_body_size 1000000;
        listen 127.0.0.1:9999;
        server_name webserv_dup2.com;

        root /home/rivoinfo/Documents/DEV/servwebs/webserv/clients/www2;
        index index.html;

        location / {
            root /home/rivoinfo/Documents/DEV/servwebs/webserv/clients/www2;
            index index.html;
            methods GET POST DELETE;
        }
    }
}
